import { SlicerType } from '../../../SlicerType';
import { ParserHelper } from '../../ParserHelper';

export interface DetectedSlicer {
    slicerType: SlicerType;
    slicerName: string;
    slicerVersion: string;
    sliceDate: string;
    sliceTime: string;
}

/**
 * Maps slicer name strings (from the "generated by" line) to SlicerType.
 * All unrecognised Orca-family slicers fall back to OrcaFF.
 */
const SLICER_NAME_MAP: Record<string, SlicerType> = {
    'OrcaSlicer': SlicerType.OrcaFF,
    'Orca-Flashforge': SlicerType.OrcaFF,
    'Flash Studio': SlicerType.FlashStudio,
};

/**
 * Parses an Orca-family "generated by" header line.
 *
 * Handles both single-word and multi-word slicer names:
 *   ; generated by Orca-Flashforge 1.3.0 on 2025-05-04 at 17:53:29
 *   ; generated by Flash Studio 1.7.6 on 2026-05-30 at 15:33:27
 *   ; generated by OrcaSlicer 2.3.1-beta on 2025-11-12 at 17:42:00
 *
 * @param line The raw comment line (e.g. "; generated by Flash Studio 1.7.6 ...")
 * @returns DetectedSlicer or null if the line doesn't match.
 */
export function detectSlicerFromGeneratedBy(line: string): DetectedSlicer | null {
    const cleanedLine = line.replace(/^;\s*/, '').trim();

    // Regex breakdown:
    //   generated by\s+      literal prefix
    //   (.+?)                 slicer name (lazy — handles multi-word names like "Flash Studio")
    //   \s+(\d[\d.\-]*\w*)   version (starts with digit, may contain dots/hyphens, optional tag like "beta")
    //   \s+on\s+(\S+)        date
    //   \s+at\s+(\S+)        time
    const match = cleanedLine.match(
        /^generated by\s+(.+?)\s+(\d[\d.\-]*\w*)\s+on\s+(\S+)\s+at\s+(\S+)$/
    );

    if (!match) return null;

    const [, name, version, date, time] = match;
    const slicerType = SLICER_NAME_MAP[name] ?? SlicerType.OrcaFF;

    return {
        slicerType,
        slicerName: name,
        slicerVersion: version,
        sliceDate: date,
        sliceTime: ParserHelper.parseSliceTime(time),
    };
}
